name: Upload Python Package

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.2.0 build

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist --outdir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-${{ matrix.os }}
          path: |
            wheelhouse/*.whl
            wheelhouse/*.tar.gz
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [ build_wheels ]
    permissions:
      id-token: write   # PyPI Trusted Publishing

    environment:
      name: pypi
      url: https://pypi.org/p/fastipc

    steps:
      - name: Download all release artifacts and merge
        uses: actions/download-artifact@v4
        with:
          pattern: release-dists-*
          merge-multiple: true
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
